#!/usr/bin/env bash
# nvim
alias vim='nvim'

#venv
alias venv='$HOME/src/dotfiles/bin/utils/venv.sh && source .venv/bin/activate'

# cd
alias ..='cd ..'

# git
alias gs='git status'
alias ga='git add .'
alias gd='git ls-files --deleted | xargs git rm'
alias gc='git commit'
alias gl='git log --pretty="%H %s"'
alias gp='git push'
alias gf='git difftool'
# `cd` to Git repo root
alias gr='[ ! -z `git rev-parse --show-cdup` ] && cd `git rev-parse --show-cdup || pwd`'

# copy working directory & filename
alias cwd='echo -n `pwd` | pbcopy'
alias cfn='echo -n $(basename `pwd`) | pbcopy'

# visual studio code
code() { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }

# change to random wallpaper
alias chwp='$HOME/.local/scripts/wallpaper-shuffle.sh'

# reset wifi
alias rewifi='$HOME/.local/scripts/reset-wifi.sh'

# interactive find directory and change into it
alias fd='cd "$(find $HOME -type d | fzf --preview="tree -d -C {}")"'

# interactive find (from here) directory and change to it
alias fh='cd "$(find . -type d | fzf --preview="tree -d -C {}")"'

# interactive go to file and open nvim
alias gtf='nvim $(fzf -m --preview="bat --color=always {}")'
alias slsl='systemctl --user status app-graphical.slice background-graphical.slice session.slice'
alias ax3kmon='wavemon -i wlp196s0f3u1'
