#!/usr/bin/env bash
# nvim
alias vim='nvim'

#venv
alias venv='$HOME/src/dotfiles/bin/utils/venv.sh && source .venv/bin/activate'

# source
alias reload='source ~/.zshrc'

# ls
alias l='ls -F'
alias la='ls -FA'
alias ll='ls -l'
alias lh='ls -lAh'

# cd
alias ..='cd ..'
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias d='cd ~/Desktop'
function cdl { cd $1 && ls; }

# git
alias gs='git status'
alias ga='git add .'
alias gd='git ls-files --deleted | xargs git rm'
alias gc='git commit'
alias gl='git log --pretty="%H %s"'
alias gp='git push'
alias gf='git difftool'
# `cd` to Git repo root
alias gr='[ ! -z `git rev-parse --show-cdup` ] && cd `git rev-parse --show-cdup || pwd`'

# search
alias f='find -x * -name'

# dev and src
alias gosrc='cd ~/src'

# copy working directory & filename
alias cwd='echo -n `pwd` | pbcopy'
alias cfn='echo -n $(basename `pwd`) | pbcopy'

# copy ip address to clipboard
function ip { ifconfig en1 | ruby -ne '$_.match(/inet\s((\d|\.)+)/) { print $1 }' | pbcopy; }

# unpack tar file
alias unpack='tar -xvzf'

# list out processes running on a specific port
function tcp { lsof -i tcp:$1; }

# google chrome disable same origin policy
alias chromenowebsec='open -a Google\ Chrome --args --disable-web-security'

# visual studio code
code() { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias bell="tput bel"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Recursively delete `.DS_Store` files
alias cleanup_dsstore="find . -name '*.DS_Store' -type f -ls -delete"
