#!/usr/bin/env bash

# SSH
export SSH_ENV="$HOME/.ssh/environment"

# GOPATH
export GOPATH="$HOME/go"

# Config directory
export XDG_CONFIG_HOME="$HOME/.config"

export WAYLAND_DISPLAY=wayland-1
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export GDK_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1
