#!/usr/bin/env bash

# interface for hyprpaper
sunset() {
  $HOME/.local/scripts/hyprsunset-interface.sh "$@"
}

# dotfiles install, save etc
dev() {
  $HOME/src/dotfiles/bin/dotfiles.sh "$@"
}

# venv for tmux. sends command to all panes
tmv() {
  tmux list-panes -s -F '#{pane_id}' | while read pane; do
    tmux send-keys -t "$pane" "venv" Enter
  done
}
