#!/usr/bin/env bash
echo ":: Starting 1Password install..."
if [[ ! -d "$HOME/.local/share/1password" ]]; then
  git clone https://aur.archlinux.org/1password.git $HOME/.local/share/1password
  cd $HOME/.local/share/1password
  makepkg -si
else
  echo " 1Password already installed"
fi
