#!/usr/bin/env bash
sudo pacman -Syu
echo ":: Creating necessary config and share directories..."
mkdir -p $HOME/.local/share
mkdir -p $HOME/.local/scripts
mkdir -p $HOME/.config

echo ":: Starting prerequisite package installs for dev environment..."
sudo pacman -S --noconfirm --needed --color=always \
  base-devel fzf jq man-db neofetch openssh python \
  ttf-font-awesome ttf-jetbrains-mono-nerd \
  wl-clipboard wlr-randr zathura zathura-pdf-poppler \
  git rsync zsh slurp ripgrep bat btop firefox \
  grim fwupd wavemon curl tree
