#!/usr/bin/env bash
echo ":: Starting tmux install..."
mkdir -p $XDG_CONFIG_HOME/tmux
if [[ ! -d "$XDG_CONFIG_HOME/tmux/plugins/tpm" ]]; then
  git clone https://github.com/tmux-plugins/tpm $XDG_CONFIG_HOME/tmux/plugins/tpm
else
  echo " tpm already installed"
fi
sudo pacman -S --noconfirm --needed --color=always tmux
